codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...70"
  status:
    patch:
      default:
        target: 30%
    project:
      default:
        target: 60%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
