name: master
on:
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test with Code Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install cargo-make
        uses: davidB/rust-cargo-make@v1
        with:
          version: latest
      - name: Check for formatting issues
        run: cargo make format-ci
      - name: Check for linting issues
        run: cargo make lint
      - name: Unit test with code coverage analysis
        run: cargo make test-coverage-ci
      - name: Upload test coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: lcov.info
