name: master
on:
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test and Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
      - name: Install cargo-make
        run: cargo install --force cargo-make
      - name: Unit test and code coverage
        run: cargo make test-coverage
