name: master
on:
  push:
    branches:
      - master
jobs:
  unit-test:
    name: Unit Test with Code Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true
      - name: Install cargo-make
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-make
      - name: Unit test with undefined behavior analysis
        run: cargo make miri-test
      - name: Unit test with code coverage analysis
        run: cargo make test-coverage-ci
      - name: Upload test coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: lcov.info
